services:
  # Сервис Базы Данных
  db:
    image: postgres:16
    container_name: flass_postgre
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-flass_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME:-flass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready", "-U", "flass_user", "-d", "flass"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  flass-app:
    build: .
    container_name: flass_app
    restart: always
    depends_on:
      - db
    # depends_on:
    #   db:
    #     condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Bishkek
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data: